--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false,
    secondary_emails jsonb not null default '[]'::jsonb,
    constraint sales_secondary_emails_is_array check (jsonb_typeof(secondary_emails) = 'array')
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

create table public.client_knowledge_files (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    content text not null default '',
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.recordings (
    id bigint generated by default as identity primary key,
    zoom_meeting_uuid text not null,
    topic text not null,
    start_time timestamp with time zone not null,
    duration_minutes integer not null default 0,
    host_email extensions.citext,
    attendee_emails text[] not null default '{}',
    transcript text,
    summary text,
    play_url text,
    download_url text,
    contact_id bigint,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.sessions (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    scheduled_at timestamp with time zone not null,
    duration_minutes integer not null default 60,
    status text not null default 'SCHEDULED',
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint sessions_status_check check (status in ('SCHEDULED', 'COMPLETED', 'CANCELED', 'NO_SHOW'))
);

create table public.client_activities (
    id bigint generated by default as identity primary key,
    contact_id bigint,
    sales_id bigint,
    type text not null,
    description text not null,
    created_at timestamp with time zone not null default now()
);

--
-- Foreign keys
--

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.client_knowledge_files
    add constraint client_knowledge_files_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.client_knowledge_files
    add constraint client_knowledge_files_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.recordings
    add constraint recordings_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

alter table public.recordings
    add constraint recordings_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.sessions
    add constraint sessions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.sessions
    add constraint sessions_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.client_activities
    add constraint client_activities_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

alter table public.client_activities
    add constraint client_activities_sales_id_fkey foreign key (sales_id) references public.sales(id);

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);

create unique index uq__client_knowledge_files__contact_id on public.client_knowledge_files using btree (contact_id);

create unique index uq__recordings__zoom_meeting_uuid on public.recordings using btree (zoom_meeting_uuid);
create index recordings_contact_id_idx on public.recordings using btree (contact_id);
create index recordings_start_time_idx on public.recordings using btree (start_time);

create index sessions_contact_id_idx on public.sessions using btree (contact_id);
create index sessions_scheduled_at_idx on public.sessions using btree (scheduled_at);

create index client_activities_contact_id_idx on public.client_activities using btree (contact_id);
create index client_activities_created_at_idx on public.client_activities using btree (created_at);

--
-- Email triage (Gmail inbox + AI drafts, written by the integrations server)
--

create table public.emails (
    id bigint generated by default as identity primary key,
    gmail_message_id text not null,
    gmail_thread_id text not null,
    from_email text not null,
    from_name text,
    subject text not null,
    body_text text not null default '',
    received_at timestamp with time zone not null,
    contact_id bigint,
    draft_content text,
    draft_confidence real,
    status text not null default 'PENDING',
    sent_at timestamp with time zone,
    notion_page_id text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint emails_status_check check (status in ('PENDING', 'DRAFTED', 'APPROVED', 'SENT', 'SKIPPED'))
);

alter table public.emails
    add constraint emails_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

create unique index uq__emails__gmail_message_id on public.emails using btree (gmail_message_id);
create index emails_contact_id_idx on public.emails using btree (contact_id);
create index emails_status_idx on public.emails using btree (status);
create index emails_received_at_idx on public.emails using btree (received_at);

create table public.email_agent_config (
    id integer not null default 1 primary key,
    master_prompt text not null default '',
    routing_rules text not null default '',
    style_guide text not null default '',
    updated_at timestamp with time zone not null default now(),
    constraint email_agent_config_singleton check (id = 1)
);

insert into public.email_agent_config (id) values (1);

--
-- Integration settings (Twilio/Mailgun/Stripe). Twilio/Mailgun are configuration only - nothing
-- sends yet. Stripe is live: once its keys are set, the integrations server's webhook records
-- real payments and subscriptions. Never exposed to PostgREST; see 05_policies.sql / 06_grants.sql.
--

create table public.integration_settings (
    id integer not null default 1 primary key,
    twilio_account_sid text,
    twilio_auth_token_cipher text,
    twilio_from_number text,
    sms_reminders_enabled boolean not null default false,
    mailgun_api_key_cipher text,
    mailgun_domain text,
    mailgun_from_address text,
    email_reminders_enabled boolean not null default false,
    stripe_secret_key_cipher text,
    stripe_webhook_secret_cipher text,
    updated_at timestamp with time zone not null default now(),
    constraint integration_settings_singleton check (id = 1)
);

insert into public.integration_settings (id) values (1);

--
-- Stripe payments and subscriptions (written by the integrations server's Stripe webhook)
--

create table public.payments (
    id bigint generated by default as identity primary key,
    -- Stripe invoice id ("in_...") for subscription/invoice payments, checkout session id
    -- ("cs_...") for one-off checkout payments.
    stripe_payment_id text not null,
    stripe_payment_intent_id text,
    stripe_customer_id text not null,
    customer_email extensions.citext,
    contact_id bigint,
    amount_cents integer not null,
    currency text not null default 'usd',
    status text not null,
    description text,
    paid_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint payments_status_check check (status in ('SUCCEEDED', 'FAILED', 'REFUNDED'))
);

create table public.subscriptions (
    id bigint generated by default as identity primary key,
    stripe_subscription_id text not null,
    stripe_customer_id text not null,
    customer_email extensions.citext,
    contact_id bigint,
    status text not null,
    plan_name text,
    amount_cents integer,
    currency text not null default 'usd',
    current_period_start timestamp with time zone,
    current_period_end timestamp with time zone,
    canceled_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint subscriptions_status_check check (status in ('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID'))
);

alter table public.payments
    add constraint payments_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

alter table public.subscriptions
    add constraint subscriptions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

create unique index uq__payments__stripe_payment_id on public.payments using btree (stripe_payment_id);
create index payments_stripe_payment_intent_id_idx on public.payments using btree (stripe_payment_intent_id);
create index payments_contact_id_idx on public.payments using btree (contact_id);
create index payments_paid_at_idx on public.payments using btree (paid_at);

create unique index uq__subscriptions__stripe_subscription_id on public.subscriptions using btree (stripe_subscription_id);
create index subscriptions_contact_id_idx on public.subscriptions using btree (contact_id);
create index subscriptions_status_idx on public.subscriptions using btree (status);
