-- Phase 3 of the theosyn-crm integration port: Gmail email triage.
-- See C:\Users\Milford Hutsell\.claude\plans\happy-singing-turtle.md for the full plan.
--
-- Deviations from the plan, both deliberate:
--  * Agent settings live in a dedicated singleton table instead of configuration.config jsonb
--    (the app's settings store replaces its whole config on load, which would clobber extra keys).
--  * The Notion task created from an email is recorded on emails.notion_page_id rather than a new
--    tasks column, because tasks.contact_id is NOT NULL and inbox emails are mostly from non-contacts.

create table public.emails (
    id bigint generated by default as identity primary key,
    gmail_message_id text not null,
    gmail_thread_id text not null,
    from_email text not null,
    from_name text,
    subject text not null,
    body_text text not null default '',
    received_at timestamp with time zone not null,
    contact_id bigint,
    draft_content text,
    draft_confidence real,
    status text not null default 'PENDING',
    sent_at timestamp with time zone,
    notion_page_id text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint emails_status_check check (status in ('PENDING', 'DRAFTED', 'APPROVED', 'SENT', 'SKIPPED'))
);

alter table public.emails
    add constraint emails_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

create unique index uq__emails__gmail_message_id on public.emails using btree (gmail_message_id);
create index emails_contact_id_idx on public.emails using btree (contact_id);
create index emails_status_idx on public.emails using btree (status);
create index emails_received_at_idx on public.emails using btree (received_at);

create table public.email_agent_config (
    id integer not null default 1 primary key,
    master_prompt text not null default '',
    routing_rules text not null default '',
    style_guide text not null default '',
    updated_at timestamp with time zone not null default now(),
    constraint email_agent_config_singleton check (id = 1)
);

insert into public.email_agent_config (id) values (1);

create or replace trigger set_emails_updated_at
    before update on public.emails
    for each row execute function public.set_updated_at();

create or replace trigger set_email_agent_config_updated_at
    before update on public.email_agent_config
    for each row execute function public.set_updated_at();

alter table public.emails enable row level security;
alter table public.email_agent_config enable row level security;

-- emails are only ever inserted by the integrations server (which bypasses RLS)
create policy "Enable read access for authenticated users" on public.emails for select to authenticated using (true);
create policy "Emails Update Policy" on public.emails for update to authenticated using (true);
create policy "Emails Delete Policy" on public.emails for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.email_agent_config for select to authenticated using (true);
create policy "Email Agent Config Update Policy" on public.email_agent_config for update to authenticated using (true);

grant all on table public.emails to anon;
grant all on table public.emails to authenticated;
grant all on table public.emails to service_role;

grant all on table public.email_agent_config to anon;
grant all on table public.email_agent_config to authenticated;
grant all on table public.email_agent_config to service_role;

grant all on sequence public.emails_id_seq to anon;
grant all on sequence public.emails_id_seq to authenticated;
grant all on sequence public.emails_id_seq to service_role;

-- Inbox mail and agent settings are private: nothing needs anonymous access.
revoke all on table public.emails from anon;
revoke all on table public.email_agent_config from anon;
