-- Phase 2 of the theosyn-crm integration port: sessions + activity history.
-- See C:\Users\Milford Hutsell\.claude\plans\happy-singing-turtle.md for the full plan.

create table public.sessions (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    scheduled_at timestamp with time zone not null,
    duration_minutes integer not null default 60,
    status text not null default 'SCHEDULED',
    notes text,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint sessions_status_check check (status in ('SCHEDULED', 'COMPLETED', 'CANCELED', 'NO_SHOW'))
);

create table public.client_activities (
    id bigint generated by default as identity primary key,
    contact_id bigint,
    sales_id bigint,
    type text not null,
    description text not null,
    created_at timestamp with time zone not null default now()
);

alter table public.sessions
    add constraint sessions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.sessions
    add constraint sessions_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.client_activities
    add constraint client_activities_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

alter table public.client_activities
    add constraint client_activities_sales_id_fkey foreign key (sales_id) references public.sales(id);

create index sessions_contact_id_idx on public.sessions using btree (contact_id);
create index sessions_scheduled_at_idx on public.sessions using btree (scheduled_at);

create index client_activities_contact_id_idx on public.client_activities using btree (contact_id);
create index client_activities_created_at_idx on public.client_activities using btree (created_at);

create or replace trigger set_sessions_sales_id_trigger
    before insert on public.sessions
    for each row execute function public.set_sales_id_default();

create or replace trigger set_client_activities_sales_id_trigger
    before insert on public.client_activities
    for each row execute function public.set_sales_id_default();

create or replace trigger set_sessions_updated_at
    before update on public.sessions
    for each row execute function public.set_updated_at();

alter table public.sessions enable row level security;
alter table public.client_activities enable row level security;

create policy "Enable read access for authenticated users" on public.sessions for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.sessions for insert to authenticated with check (true);
create policy "Sessions Update Policy" on public.sessions for update to authenticated using (true);
create policy "Sessions Delete Policy" on public.sessions for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.client_activities for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.client_activities for insert to authenticated with check (true);

grant all on table public.sessions to anon;
grant all on table public.sessions to authenticated;
grant all on table public.sessions to service_role;

grant all on table public.client_activities to anon;
grant all on table public.client_activities to authenticated;
grant all on table public.client_activities to service_role;

grant all on sequence public.sessions_id_seq to anon;
grant all on sequence public.sessions_id_seq to authenticated;
grant all on sequence public.sessions_id_seq to service_role;

grant all on sequence public.client_activities_id_seq to anon;
grant all on sequence public.client_activities_id_seq to authenticated;
grant all on sequence public.client_activities_id_seq to service_role;

create or replace view public.activity_log with (security_invoker = on) as
select
    ('company.' || c.id || '.created') as id,
    'company.created' as type,
    c.created_at as date,
    c.id as company_id,
    c.sales_id,
    to_json(c.*) as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note,
    null::json as client_activity
from public.companies c
union all
select
    ('contact.' || co.id || '.created') as id,
    'contact.created' as type,
    co.first_seen as date,
    co.company_id,
    co.sales_id,
    null::json as company,
    to_json(co.*) as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note,
    null::json as client_activity
from public.contacts co
union all
select
    ('contactNote.' || cn.id || '.created') as id,
    'contactNote.created' as type,
    cn.date,
    co.company_id,
    cn.sales_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    to_json(cn.*) as contact_note,
    null::json as deal_note,
    null::json as client_activity
from public.contact_notes cn
    left join public.contacts co on co.id = cn.contact_id
union all
select
    ('deal.' || d.id || '.created') as id,
    'deal.created' as type,
    d.created_at as date,
    d.company_id,
    d.sales_id,
    null::json as company,
    null::json as contact,
    to_json(d.*) as deal,
    null::json as contact_note,
    null::json as deal_note,
    null::json as client_activity
from public.deals d
union all
select
    ('dealNote.' || dn.id || '.created') as id,
    'dealNote.created' as type,
    dn.date,
    d.company_id,
    dn.sales_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    to_json(dn.*) as deal_note,
    null::json as client_activity
from public.deal_notes dn
    left join public.deals d on d.id = dn.deal_id
union all
select
    ('clientActivity.' || ca.id || '.created') as id,
    'clientActivity.' || ca.type as type,
    ca.created_at as date,
    co.company_id,
    ca.sales_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note,
    to_json(ca.*) as client_activity
from public.client_activities ca
    left join public.contacts co on co.id = ca.contact_id;
