-- Phase 4 of the theosyn-crm integration port: Stripe payment and subscription tracking.
-- See C:\Users\Milford Hutsell\.claude\plans\happy-singing-turtle.md for the full plan.
--
-- Deviations from the plan, both deliberate:
--  * No sales_id column: rows are written only by the integrations server's Stripe webhook, so they
--    have no owning CRM user.
--  * The CRM can only reassign a row to a different contact - every other column is Stripe's record
--    and is protected by a trigger (see restrict_billing_update), not just by the UI.

create table public.payments (
    id bigint generated by default as identity primary key,
    -- Stripe invoice id ("in_...") for subscription/invoice payments, checkout session id
    -- ("cs_...") for one-off checkout payments.
    stripe_payment_id text not null,
    stripe_payment_intent_id text,
    stripe_customer_id text not null,
    customer_email extensions.citext,
    contact_id bigint,
    amount_cents integer not null,
    currency text not null default 'usd',
    status text not null,
    description text,
    paid_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint payments_status_check check (status in ('SUCCEEDED', 'FAILED', 'REFUNDED'))
);

create table public.subscriptions (
    id bigint generated by default as identity primary key,
    stripe_subscription_id text not null,
    stripe_customer_id text not null,
    customer_email extensions.citext,
    contact_id bigint,
    status text not null,
    plan_name text,
    amount_cents integer,
    currency text not null default 'usd',
    current_period_start timestamp with time zone,
    current_period_end timestamp with time zone,
    canceled_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint subscriptions_status_check check (status in ('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID'))
);

alter table public.payments
    add constraint payments_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

alter table public.subscriptions
    add constraint subscriptions_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

create unique index uq__payments__stripe_payment_id on public.payments using btree (stripe_payment_id);
create index payments_stripe_payment_intent_id_idx on public.payments using btree (stripe_payment_intent_id);
create index payments_contact_id_idx on public.payments using btree (contact_id);
create index payments_paid_at_idx on public.payments using btree (paid_at);

create unique index uq__subscriptions__stripe_subscription_id on public.subscriptions using btree (stripe_subscription_id);
create index subscriptions_contact_id_idx on public.subscriptions using btree (contact_id);
create index subscriptions_status_idx on public.subscriptions using btree (status);

-- Signed-in CRM users may only change which contact a row belongs to; the integrations server
-- (a different database role) is unrestricted. Runs before set_updated_at (triggers fire by name).
create or replace function public.restrict_billing_update()
returns trigger
language plpgsql
as $$
declare
    chosen_contact_id bigint := new.contact_id;
begin
    if current_user = 'authenticated' then
        new := old;
        new.contact_id := chosen_contact_id;
    end if;
    return new;
end;
$$;

create or replace trigger "00_restrict_payments_update"
    before update on public.payments
    for each row execute function public.restrict_billing_update();

create or replace trigger "00_restrict_subscriptions_update"
    before update on public.subscriptions
    for each row execute function public.restrict_billing_update();

create or replace trigger set_payments_updated_at
    before update on public.payments
    for each row execute function public.set_updated_at();

create or replace trigger set_subscriptions_updated_at
    before update on public.subscriptions
    for each row execute function public.set_updated_at();

alter table public.payments enable row level security;
alter table public.subscriptions enable row level security;

-- Rows are only ever inserted by the integrations server (which bypasses RLS); no insert or
-- delete policy exists for signed-in users.
create policy "Enable read access for authenticated users" on public.payments for select to authenticated using (true);
create policy "Payments Update Policy" on public.payments for update to authenticated using (true);

create policy "Enable read access for authenticated users" on public.subscriptions for select to authenticated using (true);
create policy "Subscriptions Update Policy" on public.subscriptions for update to authenticated using (true);

-- Financial records are private: no anonymous access, and users can read and reassign but not
-- create or delete.
grant select, update on table public.payments to authenticated;
grant all on table public.payments to service_role;
grant select, update on table public.subscriptions to authenticated;
grant all on table public.subscriptions to service_role;
