-- Phase 1 of the theosyn-crm integration port: client knowledge files + Zoom recordings.
-- See C:\Users\Milford Hutsell\.claude\plans\happy-singing-turtle.md for the full plan.

create table public.client_knowledge_files (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    content text not null default '',
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table public.recordings (
    id bigint generated by default as identity primary key,
    zoom_meeting_uuid text not null,
    topic text not null,
    start_time timestamp with time zone not null,
    duration_minutes integer not null default 0,
    host_email extensions.citext,
    attendee_emails text[] not null default '{}',
    transcript text,
    summary text,
    play_url text,
    download_url text,
    contact_id bigint,
    sales_id bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

alter table public.client_knowledge_files
    add constraint client_knowledge_files_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.client_knowledge_files
    add constraint client_knowledge_files_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.recordings
    add constraint recordings_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete set null;

alter table public.recordings
    add constraint recordings_sales_id_fkey foreign key (sales_id) references public.sales(id);

create unique index uq__client_knowledge_files__contact_id on public.client_knowledge_files using btree (contact_id);

create unique index uq__recordings__zoom_meeting_uuid on public.recordings using btree (zoom_meeting_uuid);
create index recordings_contact_id_idx on public.recordings using btree (contact_id);
create index recordings_start_time_idx on public.recordings using btree (start_time);

CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

create or replace trigger set_client_knowledge_files_sales_id_trigger
    before insert on public.client_knowledge_files
    for each row execute function public.set_sales_id_default();

create or replace trigger set_recordings_sales_id_trigger
    before insert on public.recordings
    for each row execute function public.set_sales_id_default();

create or replace trigger set_client_knowledge_files_updated_at
    before update on public.client_knowledge_files
    for each row execute function public.set_updated_at();

create or replace trigger set_recordings_updated_at
    before update on public.recordings
    for each row execute function public.set_updated_at();

alter table public.client_knowledge_files enable row level security;
alter table public.recordings enable row level security;

create policy "Enable read access for authenticated users" on public.client_knowledge_files for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.client_knowledge_files for insert to authenticated with check (true);
create policy "Client Knowledge Files Update Policy" on public.client_knowledge_files for update to authenticated using (true);
create policy "Client Knowledge Files Delete Policy" on public.client_knowledge_files for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.recordings for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.recordings for insert to authenticated with check (true);
create policy "Recordings Update Policy" on public.recordings for update to authenticated using (true);
create policy "Recordings Delete Policy" on public.recordings for delete to authenticated using (true);

grant all on function public.set_updated_at() to anon;
grant all on function public.set_updated_at() to authenticated;
grant all on function public.set_updated_at() to service_role;

grant all on table public.client_knowledge_files to anon;
grant all on table public.client_knowledge_files to authenticated;
grant all on table public.client_knowledge_files to service_role;

grant all on table public.recordings to anon;
grant all on table public.recordings to authenticated;
grant all on table public.recordings to service_role;

grant all on sequence public.client_knowledge_files_id_seq to anon;
grant all on sequence public.client_knowledge_files_id_seq to authenticated;
grant all on sequence public.client_knowledge_files_id_seq to service_role;

grant all on sequence public.recordings_id_seq to anon;
grant all on sequence public.recordings_id_seq to authenticated;
grant all on sequence public.recordings_id_seq to service_role;
